"""rename annual_income to parents_annual_income

Revision ID: 0083b317feb2
Revises: 3503b41e9da6
Create Date: 2026-03-31 18:44:13.059533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0083b317feb2'
down_revision: Union[str, Sequence[str], None] = '3503b41e9da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_details', sa.Column('parents_annual_income', sa.String(), nullable=True))
    op.drop_column('applicant_details', 'annual_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_details', sa.Column('annual_income', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applicant_details', 'parents_annual_income')
    # ### end Alembic commands ###
