"""Rename columns to full names

Revision ID: 5d9491c5bbc4
Revises: 0083b317feb2
Create Date: 2026-04-02 20:08:01.382306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9491c5bbc4'
down_revision: Union[str, Sequence[str], None] = '0083b317feb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('application_id', sa.Integer(), nullable=True))
    op.execute('UPDATE applications SET application_id = app_id')
    op.execute('ALTER TABLE applications ALTER COLUMN application_id SET NOT NULL')
    op.execute('ALTER TABLE applications DROP CONSTRAINT applications_pkey CASCADE')
    op.execute('ALTER TABLE applications ADD PRIMARY KEY (application_id)')
    op.drop_index(op.f('ix_applications_app_id'), table_name='applications')
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=False)
    op.drop_column('applications', 'app_id')
    op.add_column('applicant_details', sa.Column('application_id', sa.Integer(), nullable=True))
    op.execute('UPDATE applicant_details SET application_id = app_id')
    op.drop_constraint(op.f('applicant_details_app_id_key'), 'applicant_details', type_='unique')
    op.create_unique_constraint(None, 'applicant_details', ['application_id'])
    op.execute('ALTER TABLE applicant_details DROP CONSTRAINT IF EXISTS applicant_details_app_id_fkey')
    op.create_foreign_key(None, 'applicant_details', 'applications', ['application_id'], ['application_id'])
    op.drop_column('applicant_details', 'app_id')
    op.add_column('brochure_requests', sa.Column('brochure_id', sa.Integer(), nullable=True))
    op.execute('UPDATE brochure_requests SET brochure_id = bro_id')
    op.execute('ALTER TABLE brochure_requests ALTER COLUMN brochure_id SET NOT NULL')
    op.execute('ALTER TABLE brochure_requests DROP CONSTRAINT brochure_requests_pkey CASCADE')
    op.execute('ALTER TABLE brochure_requests ADD PRIMARY KEY (brochure_id)')
    op.add_column('brochure_requests', sa.Column('status', sa.String(), nullable=True))
    op.execute('UPDATE brochure_requests SET status = bro_status')
    op.add_column('brochure_requests', sa.Column('payment_status', sa.String(), nullable=True))
    op.execute('UPDATE brochure_requests SET payment_status = bro_payment')
    op.drop_index(op.f('ix_brochure_requests_bro_id'), table_name='brochure_requests')
    op.create_index(op.f('ix_brochure_requests_brochure_id'), 'brochure_requests', ['brochure_id'], unique=False)
    op.drop_column('brochure_requests', 'bro_id')
    op.drop_column('brochure_requests', 'bro_status')
    op.drop_column('brochure_requests', 'bro_payment')
    op.add_column('courses', sa.Column('department_id', sa.Integer(), nullable=True))
    op.execute('UPDATE courses SET department_id = dept_id')
    op.drop_column('courses', 'dept_id')
    op.add_column('education_details', sa.Column('education_id', sa.Integer(), nullable=True))
    op.execute('UPDATE education_details SET education_id = edu_id')
    op.execute('ALTER TABLE education_details ALTER COLUMN education_id SET NOT NULL')
    op.execute('ALTER TABLE education_details DROP CONSTRAINT education_details_pkey CASCADE')
    op.execute('ALTER TABLE education_details ADD PRIMARY KEY (education_id)')
    op.add_column('education_details', sa.Column('application_id', sa.Integer(), nullable=True))
    op.execute('UPDATE education_details SET application_id = app_id')
    op.drop_index(op.f('ix_education_details_edu_id'), table_name='education_details')
    op.create_index(op.f('ix_education_details_education_id'), 'education_details', ['education_id'], unique=False)
    op.execute('ALTER TABLE education_details DROP CONSTRAINT IF EXISTS education_details_app_id_fkey')
    op.create_foreign_key(None, 'education_details', 'applications', ['application_id'], ['application_id'])
    op.drop_column('education_details', 'edu_id')
    op.drop_column('education_details', 'app_id')
    op.add_column('parent_details', sa.Column('application_id', sa.Integer(), nullable=True))
    op.execute('UPDATE parent_details SET application_id = app_id')
    op.execute('ALTER TABLE parent_details DROP CONSTRAINT IF EXISTS parent_details_app_id_fkey')
    op.create_foreign_key(None, 'parent_details', 'applications', ['application_id'], ['application_id'])
    op.drop_column('parent_details', 'app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_details', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parent_details', type_='foreignkey')
    op.create_foreign_key(op.f('parent_details_app_id_fkey'), 'parent_details', 'applications', ['app_id'], ['app_id'])
    op.drop_column('parent_details', 'application_id')
    op.add_column('education_details', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education_details', sa.Column('edu_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'education_details', type_='foreignkey')
    op.create_foreign_key(op.f('education_details_app_id_fkey'), 'education_details', 'applications', ['app_id'], ['app_id'])
    op.drop_index(op.f('ix_education_details_education_id'), table_name='education_details')
    op.create_index(op.f('ix_education_details_edu_id'), 'education_details', ['edu_id'], unique=False)
    op.drop_column('education_details', 'application_id')
    op.drop_column('education_details', 'education_id')
    op.add_column('courses', sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'department_id')
    op.add_column('brochure_requests', sa.Column('bro_payment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brochure_requests', sa.Column('bro_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brochure_requests', sa.Column('bro_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_brochure_requests_brochure_id'), table_name='brochure_requests')
    op.create_index(op.f('ix_brochure_requests_bro_id'), 'brochure_requests', ['bro_id'], unique=False)
    op.drop_column('brochure_requests', 'payment_status')
    op.drop_column('brochure_requests', 'status')
    op.drop_column('brochure_requests', 'brochure_id')
    op.add_column('applications', sa.Column('app_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.create_index(op.f('ix_applications_app_id'), 'applications', ['app_id'], unique=False)
    op.drop_column('applications', 'application_id')
    op.add_column('applicant_details', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applicant_details', type_='foreignkey')
    op.create_foreign_key(op.f('applicant_details_app_id_fkey'), 'applicant_details', 'applications', ['app_id'], ['app_id'])
    op.drop_constraint(None, 'applicant_details', type_='unique')
    op.create_unique_constraint(op.f('applicant_details_app_id_key'), 'applicant_details', ['app_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('applicant_details', 'application_id')
    # ### end Alembic commands ###
