"""Add Batch A Advanced Admission tables

Revision ID: 806e5718b345
Revises: b42e5b2308db
Create Date: 2026-03-31 17:40:27.129278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806e5718b345'
down_revision: Union[str, Sequence[str], None] = 'b42e5b2308db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brochure_requests',
    sa.Column('bro_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('bro_status', sa.String(), nullable=True),
    sa.Column('bro_payment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bro_id')
    )
    op.create_index(op.f('ix_brochure_requests_bro_id'), 'brochure_requests', ['bro_id'], unique=False)
    op.create_table('applicant_details',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('disability_status', sa.String(), nullable=True),
    sa.Column('aadhaar_no', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('annual_income', sa.String(), nullable=True),
    sa.Column('caste_category', sa.String(), nullable=True),
    sa.Column('hostel_required', sa.Boolean(), nullable=True),
    sa.Column('scholarship_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ),
    sa.PrimaryKeyConstraint('applicant_id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_index(op.f('ix_applicant_details_applicant_id'), 'applicant_details', ['applicant_id'], unique=False)
    op.create_table('education_details',
    sa.Column('edu_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('qualification_level', sa.String(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('university_board', sa.String(), nullable=True),
    sa.Column('percentage_result', sa.String(), nullable=True),
    sa.Column('admission_year', sa.String(), nullable=True),
    sa.Column('passout_year', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('stream', sa.String(), nullable=True),
    sa.Column('gap', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ),
    sa.PrimaryKeyConstraint('edu_id')
    )
    op.create_index(op.f('ix_education_details_edu_id'), 'education_details', ['edu_id'], unique=False)
    op.create_table('parent_details',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_type', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_parent_details_parent_id'), 'parent_details', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_details_parent_id'), table_name='parent_details')
    op.drop_table('parent_details')
    op.drop_index(op.f('ix_education_details_edu_id'), table_name='education_details')
    op.drop_table('education_details')
    op.drop_index(op.f('ix_applicant_details_applicant_id'), table_name='applicant_details')
    op.drop_table('applicant_details')
    op.drop_index(op.f('ix_brochure_requests_bro_id'), table_name='brochure_requests')
    op.drop_table('brochure_requests')
    # ### end Alembic commands ###
