"""Add role to user and approval statuses to application

Revision ID: b42e5b2308db
Revises: 31ddc87cd211
Create Date: 2026-03-31 17:21:11.776021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42e5b2308db'
down_revision: Union[str, Sequence[str], None] = '31ddc87cd211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('form_approval', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('fee_approval', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('document_approval', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('subject_approval', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('applications', 'subject_approval')
    op.drop_column('applications', 'document_approval')
    op.drop_column('applications', 'fee_approval')
    op.drop_column('applications', 'form_approval')
    # ### end Alembic commands ###
