"""refactor_document_management

Revision ID: 4599598a492e
Revises: e514b36c6319
Create Date: 2026-03-31 16:28:58.669673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4599598a492e'
down_revision: Union[str, None] = 'e514b36c6319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_app_id', table_name='application')
    op.create_index(op.f('ix_application_application_id'), 'application', ['application_id'], unique=False)
    op.drop_index('ix_brochure_request_bro_id', table_name='brochure_request')
    op.create_index(op.f('ix_brochure_request_brochure_id'), 'brochure_request', ['brochure_id'], unique=False)
    op.add_column('documents', sa.Column('document_name', sa.String(length=150), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_education_details_edu_id', table_name='education_details')
    op.create_index(op.f('ix_education_details_education_id'), 'education_details', ['education_id'], unique=False)
    op.drop_index('ix_enrollment_en_id', table_name='enrollment')
    op.create_index(op.f('ix_enrollment_enrollment_id'), 'enrollment', ['enrollment_id'], unique=False)
    op.create_unique_constraint(None, 'parent_details', ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_details', type_='unique')
    op.drop_index(op.f('ix_enrollment_enrollment_id'), table_name='enrollment')
    op.create_index('ix_enrollment_en_id', 'enrollment', ['enrollment_id'], unique=False)
    op.drop_index(op.f('ix_education_details_education_id'), table_name='education_details')
    op.create_index('ix_education_details_edu_id', 'education_details', ['education_id'], unique=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'document_name')
    op.drop_index(op.f('ix_brochure_request_brochure_id'), table_name='brochure_request')
    op.create_index('ix_brochure_request_bro_id', 'brochure_request', ['brochure_id'], unique=False)
    op.drop_index(op.f('ix_application_application_id'), table_name='application')
    op.create_index('ix_application_app_id', 'application', ['application_id'], unique=False)
    # ### end Alembic commands ###
