"""Initial_Fresh_Schema

Revision ID: f171574b9e84
Revises: 
Create Date: 2026-03-28 00:24:31.274355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f171574b9e84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_course_id'), 'course', ['course_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('brochure_request',
    sa.Column('bro_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('bro_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('bro_id')
    )
    op.create_index(op.f('ix_brochure_request_bro_id'), 'brochure_request', ['bro_id'], unique=False)
    op.create_table('application',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bro_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bro_id'], ['brochure_request.bro_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_application_app_id'), 'application', ['app_id'], unique=False)
    op.create_table('bro_payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bro_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bro_id'], ['brochure_request.bro_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_bro_payment_payment_id'), 'bro_payment', ['payment_id'], unique=False)
    op.create_table('admin_review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_admin_review_review_id'), 'admin_review', ['review_id'], unique=False)
    op.create_table('applicant_details',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('abc_id', sa.String(length=50), nullable=True),
    sa.Column('adhar_no', sa.String(length=12), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('caste_category', sa.String(length=50), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('hosteller_or_dayscholar', sa.String(length=20), nullable=True),
    sa.Column('is_scholarship_student', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('account_no', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('lc_tc_path', sa.String(length=500), nullable=True),
    sa.Column('caste_cert_path', sa.String(length=500), nullable=True),
    sa.Column('passout_result_path', sa.String(length=500), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('applicant_id'),
    sa.UniqueConstraint('adhar_no'),
    sa.UniqueConstraint('app_id')
    )
    op.create_index(op.f('ix_applicant_details_applicant_id'), 'applicant_details', ['applicant_id'], unique=False)
    op.create_table('application_status_log',
    sa.Column('status_log_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_role', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('status_log_id')
    )
    op.create_index(op.f('ix_application_status_log_status_log_id'), 'application_status_log', ['status_log_id'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=False)
    op.create_table('education_details',
    sa.Column('edu_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('qualification_level', sa.String(length=50), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('university_board', sa.String(length=150), nullable=False),
    sa.Column('passout_year', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('obtained_marks', sa.Integer(), nullable=True),
    sa.Column('percentage_result', sa.Float(), nullable=True),
    sa.Column('batch', sa.String(length=50), nullable=True),
    sa.Column('stream', sa.String(length=50), nullable=True),
    sa.Column('previous_college_name', sa.String(length=200), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('edu_id')
    )
    op.create_index(op.f('ix_education_details_edu_id'), 'education_details', ['edu_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('en_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('en_status', sa.String(length=50), nullable=True),
    sa.Column('en_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('en_id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_index(op.f('ix_enrollment_en_id'), 'enrollment', ['en_id'], unique=False)
    op.create_table('parent_details',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('parent_relationship', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mob_no', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_parent_details_parent_id'), 'parent_details', ['parent_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    op.create_table('document_verification',
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.doc_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_document_verification_verification_id'), 'document_verification', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_verification_verification_id'), table_name='document_verification')
    op.drop_table('document_verification')
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_parent_details_parent_id'), table_name='parent_details')
    op.drop_table('parent_details')
    op.drop_index(op.f('ix_enrollment_en_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_education_details_edu_id'), table_name='education_details')
    op.drop_table('education_details')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_application_status_log_status_log_id'), table_name='application_status_log')
    op.drop_table('application_status_log')
    op.drop_index(op.f('ix_applicant_details_applicant_id'), table_name='applicant_details')
    op.drop_table('applicant_details')
    op.drop_index(op.f('ix_admin_review_review_id'), table_name='admin_review')
    op.drop_table('admin_review')
    op.drop_index(op.f('ix_bro_payment_payment_id'), table_name='bro_payment')
    op.drop_table('bro_payment')
    op.drop_index(op.f('ix_application_app_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_brochure_request_bro_id'), table_name='brochure_request')
    op.drop_table('brochure_request')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_course_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
